# Generated by Django 4.2.5 on 2023-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primark', '0002_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
